/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Editorial Gravitas — landing/auth/dashboard
        paper: "#f4ecda",
        "paper-2": "#ecdfc2",
        "paper-3": "#dfc9a0",
        ink: "#0e1a2b",
        "ink-2": "#1b2d45",
        "ink-soft": "#4a5468",
        rule: "#c7b894",
        brass: "#b68b3c",
        "brass-deep": "#8e6a24",
        vermillion: "#b43a2c",

        // Pocket Plex — global admin section
        "admin-bg": "#fafaf7",
        "admin-surface": "#ffffff",
        "admin-border": "#e8e6e0",
        "admin-border-soft": "#f0ede6",
        "admin-fg": "#0e1a1f",
        "admin-fg-muted": "#5a6470",
        "admin-fg-soft": "#8a929e",
        "admin-accent": "#0e7c4a",
        "admin-accent-hover": "#0a6238",
        "admin-accent-soft": "#e6f2ec",
        "admin-saffron": "#e5803a",
        "admin-saffron-soft": "#faefe3",
        "admin-danger": "#c9382f",
        "admin-danger-soft": "#fbeae7",
        "admin-warning": "#b7791f",
        "admin-warning-soft": "#fbf3e0",

        // Midnight Counsel — partner-side app
        "app-canvas": "#f4ede0",
        "app-canvas-2": "#efe5d0",
        "app-paper": "#ffffff",
        "app-paper-2": "#faf6ed",
        "app-edge": "#e3d9c0",
        "app-edge-soft": "#efe5d0",
        "app-ink": "#0a1124",
        "app-ink-2": "#141d33",
        "app-ink-3": "#1f2a45",
        "app-ivory": "#f5ebd6",
        "app-ivory-soft": "#c4baa3",
        "app-ivory-dim": "#7e7763",
        "app-fg": "#0a1124",
        "app-fg-soft": "#4d4538",
        "app-fg-muted": "#7a7060",
        "app-copper": "#c5853a",
        "app-copper-warm": "#d28a3c",
        "app-copper-bright": "#ddb074",
        "app-copper-deep": "#8a5821",
        "app-copper-text": "#2a1c08",
        "app-aqua": "#56a0a8",
        "app-aqua-soft": "#d2e6e7",
        "app-danger": "#c14a37",
        "app-danger-soft": "#f6dccd",
        "app-success": "#6c9858",
      },
      fontFamily: {
        display: ["Fraunces-Medium"],
        "display-italic": ["Fraunces-MediumItalic"],
        "display-bold": ["Fraunces-SemiBold"],
        body: ["Newsreader"],
        "body-italic": ["Newsreader-Italic"],
        mono: ["JetBrainsMono"],
        "mono-medium": ["JetBrainsMono-Medium"],
        // Plex — admin section
        plex: ["PlexSans"],
        "plex-medium": ["PlexSans-Medium"],
        "plex-bold": ["PlexSans-SemiBold"],
        "plex-mono": ["PlexMono"],
        "plex-mono-medium": ["PlexMono-Medium"],
        // Midnight Counsel — partner app
        crimson: ["Crimson"],
        "crimson-italic": ["Crimson-Italic"],
        "crimson-bold": ["Crimson-SemiBold"],
        "crimson-bold-italic": ["Crimson-SemiBoldItalic"],
        manrope: ["Manrope"],
        "manrope-medium": ["Manrope-Medium"],
        "manrope-bold": ["Manrope-SemiBold"],
        "manrope-extrabold": ["Manrope-Bold"],
        "dm-mono": ["DMMono"],
        "dm-mono-medium": ["DMMono-Medium"],
      },
    },
  },
  plugins: [],
};
